# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
      
version: 2
enable-beta-ecosystems: true
updates:

  # Update dependencies for Pub package ecosystem
  - package-ecosystem: "pub"
    directory: "/" # Adjust the location of package manifests
    schedule:
      interval: "daily"
      
  # Update GitHub Actions workflow files
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"      

  # Update Terraform modules and providers
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Update Python packages managed by pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Only update the lockfile for pip and ignore manifest changes
    versioning-strategy: lockfile-only

# Additional global configuration options can be added here if needed
# etc.
